export const docsManifest = [
  {
    section: "start",
    sectionTitle: "Start",
    slug: "overview",
    title: "Overview",
    description:
      "Learn what Gigatable provides and choose the right path through the docs.",
    sourceFile: "overview.md",
    keywords: ["introduction", "features", "react", "spreadsheet", "grid"],
    audience: "consumer",
  },
  {
    section: "start",
    sectionTitle: "Start",
    slug: "installation",
    title: "Installation",
    description: "Install Gigatable with npm, pnpm, yarn, or bun.",
    sourceFile: "installation.md",
    keywords: ["install", "cli", "requirements", "tailwind", "typescript"],
    audience: "consumer",
  },
  {
    section: "start",
    sectionTitle: "Start",
    slug: "quickstart",
    title: "Quickstart",
    description: "Render an editable, selectable table in a few minutes.",
    sourceFile: "quickstart.md",
    keywords: ["setup", "example", "first table", "column definitions"],
    audience: "consumer",
  },
  {
    section: "guides",
    sectionTitle: "Guides",
    slug: "columns-editing",
    title: "Columns & Editing",
    description: "Define typed columns, editable cells, and commit behavior.",
    sourceFile: "columns-editing.md",
    keywords: ["columns", "editable", "input", "cell", "allColumnsEditable"],
    audience: "consumer",
  },
  {
    section: "guides",
    sectionTitle: "Guides",
    slug: "selection-navigation",
    title: "Selection & Navigation",
    description: "Configure cell, range, and single-column selection.",
    sourceFile: "selection-navigation.md",
    keywords: ["selection", "range", "keyboard", "arrow", "tab"],
    audience: "consumer",
  },
  {
    section: "guides",
    sectionTitle: "Guides",
    slug: "clipboard-paste",
    title: "Clipboard & Paste",
    description: "Copy TSV ranges, parse values, and inspect paste changes.",
    sourceFile: "clipboard-paste.md",
    keywords: ["clipboard", "copy", "paste", "tsv", "parsePastedValue"],
    audience: "consumer",
  },
  {
    section: "guides",
    sectionTitle: "Guides",
    slug: "fill-handle",
    title: "Fill Handle",
    description: "Repeat values vertically, horizontally, or in both axes.",
    sourceFile: "fill-handle.md",
    keywords: ["fill", "drag", "horizontal", "vertical", "preview"],
    audience: "consumer",
  },
  {
    section: "guides",
    sectionTitle: "Guides",
    slug: "history-clearing",
    title: "History & Clearing",
    description: "Enable undo/redo and customize Delete or Backspace values.",
    sourceFile: "history-clearing.md",
    keywords: ["history", "undo", "redo", "clear", "delete", "backspace"],
    audience: "consumer",
  },
  {
    section: "guides",
    sectionTitle: "Guides",
    slug: "column-resizing",
    title: "Column Resizing",
    description: "Enable resizing and persist TanStack column sizing state.",
    sourceFile: "column-resizing.md",
    keywords: ["resize", "width", "columnSizing", "persist"],
    audience: "consumer",
  },
  {
    section: "guides",
    sectionTitle: "Guides",
    slug: "virtualization-performance",
    title: "Virtualization & Performance",
    description: "Understand row virtualization and keep large grids fast.",
    sourceFile: "virtualization-performance.md",
    keywords: ["virtualization", "performance", "large data", "overscan"],
    audience: "consumer",
  },
  {
    section: "customization",
    sectionTitle: "Customization",
    slug: "theming",
    title: "Theming",
    description: "Use presets, typed overrides, and CSS custom properties.",
    sourceFile: "theming.md",
    keywords: ["theme", "light", "dark", "minimal", "giga", "css variables"],
    audience: "consumer",
  },
  {
    section: "customization",
    sectionTitle: "Customization",
    slug: "column-metadata",
    title: "Column Metadata",
    description:
      "Customize parsing, clearing, fill previews, and cell classes.",
    sourceFile: "column-metadata.md",
    keywords: ["metadata", "parse", "clear", "className", "allowFill"],
    audience: "consumer",
  },
  {
    section: "customization",
    sectionTitle: "Customization",
    slug: "custom-inputs",
    title: "Custom Inputs",
    description: "Build text, numeric, select, and domain-specific editors.",
    sourceFile: "custom-inputs.md",
    keywords: ["input", "editor", "select", "number", "onValueChange"],
    audience: "consumer",
  },
  {
    section: "customization",
    sectionTitle: "Customization",
    slug: "composition",
    title: "Compound Composition",
    description: "Replace table layers while retaining Gigatable behavior.",
    sourceFile: "composition.md",
    keywords: ["compound", "custom body", "footer", "cell", "children"],
    audience: "consumer",
  },
  {
    section: "customization",
    sectionTitle: "Customization",
    slug: "context-quick-edit",
    title: "Context & Quick Edit",
    description: "Integrate custom renderers, scrollers, and text selection.",
    sourceFile: "context-quick-edit.md",
    keywords: ["context", "useGigatableContext", "useQuickEdit", "scroller"],
    audience: "consumer",
  },
  {
    section: "reference",
    sectionTitle: "Reference",
    slug: "gigatable-api",
    title: "Gigatable",
    description: "Reference every Gigatable component prop and default.",
    sourceFile: "gigatable-api.md",
    keywords: ["props", "component", "api", "containerRef", "tableStyle"],
    audience: "consumer",
  },
  {
    section: "reference",
    sectionTitle: "Reference",
    slug: "use-gigatable-api",
    title: "useGigatable",
    description:
      "Reference hook options, return values, and mutation handlers.",
    sourceFile: "use-gigatable-api.md",
    keywords: ["hook", "api", "options", "return", "handlers"],
    audience: "consumer",
  },
  {
    section: "reference",
    sectionTitle: "Reference",
    slug: "editable-cell-api",
    title: "EditableCell",
    description: "Reference the editable wrapper and custom input contract.",
    sourceFile: "editable-cell-api.md",
    keywords: ["editablecell", "renderInput", "input props", "api"],
    audience: "consumer",
  },
  {
    section: "reference",
    sectionTitle: "Reference",
    slug: "hooks-context-api",
    title: "Hooks & Context",
    description: "Reference composition context, cell state, and quick edit.",
    sourceFile: "hooks-context-api.md",
    keywords: ["context", "quick edit", "cell state", "feature guide"],
    audience: "consumer",
  },
  {
    section: "reference",
    sectionTitle: "Reference",
    slug: "types",
    title: "Exported Types",
    description: "Use Gigatable’s exported TypeScript types.",
    sourceFile: "types.md",
    keywords: ["types", "typescript", "paste result", "selection"],
    audience: "consumer",
  },
  {
    section: "reference",
    sectionTitle: "Reference",
    slug: "keyboard-shortcuts",
    title: "Keyboard Shortcuts",
    description: "Reference every mouse and keyboard interaction.",
    sourceFile: "keyboard-shortcuts.md",
    keywords: ["keyboard", "shortcut", "mouse", "command", "control"],
    audience: "consumer",
  },
  {
    section: "contributing",
    sectionTitle: "Contributing",
    slug: "contributor-overview",
    title: "Internals Overview",
    description: "Understand source ownership and package boundaries.",
    sourceFile: "contributor-overview.md",
    keywords: ["internals", "source", "architecture"],
    audience: "contributor",
  },
  {
    section: "contributing",
    sectionTitle: "Contributing",
    slug: "contributor-file-map",
    title: "File Map",
    description: "Find the module responsible for each behavior.",
    sourceFile: "contributor-file-map.md",
    keywords: ["files", "modules", "ownership"],
    audience: "contributor",
  },
  {
    section: "contributing",
    sectionTitle: "Contributing",
    slug: "contributor-architecture",
    title: "Architecture",
    description: "Follow state, rendering, and virtualization data flow.",
    sourceFile: "contributor-architecture.md",
    keywords: ["architecture", "data flow", "virtualizer"],
    audience: "contributor",
  },
  {
    section: "contributing",
    sectionTitle: "Contributing",
    slug: "contributor-interactions",
    title: "Interaction Internals",
    description: "Trace selection, editing, clipboard, fill, and history.",
    sourceFile: "contributor-interactions.md",
    keywords: ["interactions", "selection", "editing", "history"],
    audience: "contributor",
  },
  {
    section: "contributing",
    sectionTitle: "Contributing",
    slug: "contributor-theming-distribution",
    title: "Theming & Distribution",
    description: "Understand theme tokens, CLI sync, and release flow.",
    sourceFile: "contributor-theming-distribution.md",
    keywords: ["distribution", "cli", "publish", "theme"],
    audience: "contributor",
  },
] as const;

export type DocsManifestEntry = (typeof docsManifest)[number];
export type DocsSlug = DocsManifestEntry["slug"];
export type DocsSectionId = DocsManifestEntry["section"];

export const defaultDocsSlug: DocsSlug = "overview";

export function isDocsSlug(value: string): value is DocsSlug {
  return docsManifest.some((entry) => entry.slug === value);
}
